name: Build And Deploy BackEnd Code To AWS EC2
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - name: CheckOut
        uses: actions/checkout@v3
      
      - name: Set up JDK 1.8
        uses: actions/set-up-java@v1
        with:
          java-version: 1.8
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      
      - name: Build with Gradle
        run: ./gradlew clean build
